# Generated by Django 3.1.2 on 2020-10-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeamate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(blank=True, max_length=200)),
                ('title2', models.CharField(blank=True, max_length=100)),
                ('link1', models.ImageField(blank=True, upload_to='logo_of_teamate')),
                ('title1', models.CharField(blank=True, max_length=100)),
                ('img2', models.CharField(blank=True, max_length=200)),
                ('link2', models.ImageField(blank=True, upload_to='logo_of_teamate')),
                ('title3', models.CharField(blank=True, max_length=100)),
                ('img3', models.CharField(blank=True, max_length=200)),
                ('link3', models.ImageField(blank=True, upload_to='logo_of_teamate')),
                ('title4', models.CharField(blank=True, max_length=100)),
                ('img4', models.CharField(blank=True, max_length=200)),
                ('link4', models.ImageField(blank=True, upload_to='logo_of_teamate')),
            ],
        ),
    ]
